itech-group-t/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from vinyldestination import views

urlpatterns = [
	path('', views.index, name='index'),
	path('vinyldestination/', include('vinyldestination.urls')),
	# The above maps any URLs starting with vinyldestination/ to be handled by vinyldestination.
    path('oauth/', include('social_django.urls')), 
    path('admin/', admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings'), name='ratings'),
    path('settings/', views.settings, name='settings'),
    path('settings/password/', views.password, name='password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
	path('', views.index, name='index'),
	path('rango/', include('rango.urls')),
	# The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinyl_destination/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
	path('', views.index, name='index'),
	path('rango/', include('rango.urls')),
	# The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinyldestination/urls.py
from django.conf.urls import url
from django.urls import path
from django.urls import include
from vinyldestination import views

app_name = 'vinyldestination'
urlpatterns = [
    path('', views.index, name='index'),
    path('artists/', views.artists, name='artists'),
    path('records/', views.records, name='records'),
    path('records/<slug:record_name_slug>/', views.show_record,
        name='show_record'),
    path('records/<slug:record_name_slug>/add_review/', views.add_review,
        name='add_review'),
    path('artists/<slug:artist_name_slug>/', views.show_artist,
        name='show_artist'),
    path('register/', views.register, name='register'), 
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

vinyldestination/forms.py
from django import forms
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from django.conf import settings
from vinyldestination.models import Page, Artist, UserProfile, Review

class ArtistForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the artist's name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide
    class Meta:
        # Provide an association
        model = Artist
        fields = ('name',)


class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=50, help_text="Please give your review a title.")
    review = forms.TextInput()
    
    
    # def __init__(self, *args, **kwargs):
    #     super(ReviewForm, self).__init__(*args, **kwargs)
    #     self.fields['author'].initial = self.data

    class Meta:
        model = Review
        fields = ('title', 'review')


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
# or specify the fields to include (don't include the category field).
# fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

vinyldestination/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from vinyldestination.models import Artist, Record, Review
from vinyldestination.forms import ArtistForm, PageForm, UserForm, UserProfileForm, ReviewForm
from star_ratings.models import Rating
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.conf import settings
from social_django.models import UserSocialAuth
from django.http import HttpResponseRedirect


# Create your views here.
def index(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

        artist_list = Artist.objects.order_by('-likes')[:5]
        trending_list = Record.objects.order_by('-views')[:10]
        record_list = Record.objects.order_by('-ratings__average')[:10]

        # Construct a dictionary to pass to the template engine as its context.
        # Note the key boldmessage matches to {{ boldmessage }} in the template!
        context_dict = {}
        context_dict['artists'] = artist_list
        context_dict['trending'] = trending_list
        context_dict['records'] = record_list
        context_dict['user_form'] = user_form
        context_dict['profile_form'] = profile_form
        visitor_cookie_handler(request)

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier. # Note that the first parameter is the template we wish to use.
    response = render(request, 'vinyldestination/index.html', context=context_dict)
    return response


@login_required
def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'vinyldestination/settings.html', {
        'github_login': github_login,
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'vinyldestination/password.html', {'form': form})


@login_required
def restricted(request):
    return render(request, 'vinyldestination/restricted.html', {})


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    request.session['visits'] = visits


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/vinyldestination/')
        else:
            print(form.errors)

    return render(request, 'vinyldestination/add_category.html', {'form': form})


def show_artist(request, artist_name_slug):
    context_dict = {}

    try:
        artist = Artist.objects.get(slug=artist_name_slug)

        record = Record.objects.filter(artist=artist)

        context_dict['artist'] = artist
        context_dict['records'] = record
    except Artist.DoesNotExist:
        context_dict['artist'] = None
        context_dict['records'] = None

    return render(request, 'vinyldestination/artist.html', context=context_dict)


@login_required
def add_review(request, record_name_slug):
    record = Record.objects.get(slug=record_name_slug)
    author = request.user
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.author = author
            review.record = record
            review_form.save()
            return HttpResponseRedirect(reverse('vinyldestination:show_record', args=(record_name_slug,)))
        else:
            print(review_form.errors)
    else:
        review_form = ReviewForm()
    context_dict = {}
    context_dict['review_form'] = review_form
    context_dict['record'] = record
    return render(request, 'vinyldestination/add_review.html', context=context_dict)


def artists(request):
    context_dict = {}
    artist_list = Artist.objects

    context_dict['artists'] = artist_list
    visitor_cookie_handler(request)

    response = render(request, 'vinyldestination/artists.html', context=context_dict)
    return response


def records(request):
    context_dict = {}
    record_list = Record.objects.order_by('-likes')[:10]
    all_record_list = Record.objects.order_by('name')

    context_dict['records_pop'] = record_list
    context_dict['records_all'] = all_record_list

    visitor_cookie_handler(request)

    response = render(request, 'vinyldestination/records.html', context=context_dict)
    return response


def show_record(request, record_name_slug):
    context_dict = {}

    try:
        record = Record.objects.get(slug=record_name_slug)
        artist = Artist.objects.get(name=record.a_id)
        similar = Record.objects.filter(genre=record.genre).exclude(name=record.name)
        review = Review.objects.filter(record=record)

        context_dict['record'] = record
        context_dict['artist'] = artist
        context_dict['similar'] = similar
        context_dict['review'] = review
    except Record.DoesNotExist:
        context_dict['record'] = None
        context_dict['artist'] = None
        context_dict['similar'] = None
        context_dict['review'] = None

    return render(request, 'vinyldestination/record.html', context=context_dict)


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            # Now we save the UserProfile model instance.
            profile.save()
            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:

templates/vinyldestination/add_review.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block head %}
<link href="{% static 'css/basic/final_review.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
{% endblock %}

{% block title_block %}
Review {{record.name}}
{% endblock %}

{% block body_block %}

<a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>

<div class="container">

	<div class = "block">
		<img id="singleimage" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
	</div>

	<div class = "block">
	<form id="review_form" method="post"
		  enctype="multipart/form-data">
		<h3>You are logged in as {{ user.username }}</h3>
		<h3>You are leaving a review for {{record.name}} by {{record.a_id}}</h3>
		{% csrf_token %}
		{{ review_form.non_field_errors }}

		<div class="fieldWrapper">
			<label for="{{ review_form.title.id_for_label }}">Title of review:</label></br>
			{{ review_form.title }}
		</div>
		<br>

		<div class="fieldWrapper">
			{{ review_form.non_field.errors }}
			<label for="{{ form.review.id_for_label }}">Your review:</label></br>
			{{ review_form.review }}
		</div>
		<br>
		<center><input type="submit" id="button" name="submit" value="Submit Review" /><center>
	</form>
	</div>
</div>

{% endblock %}

templates/vinyldestination/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load vinyldestination_template_tags %}
{% load static %}
<html>

<head>
	{% block head %}
	<link href="{% static 'css/basic/final_base.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
	<link href="{% static 'star-ratings/css/star-ratings.css' %}" rel="stylesheet">
	<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.js' %}"></script>
	{% endblock %}
		<title>
            {% block title_block %}
			{% endblock %}
		</title>
</head>

<body>

	<div class = "nav">
		<div class = "header">
		<a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>
		</div>
		<div class = "menu">
			{% if user.is_authenticated %}
			<ul id="options">
				<li><a href="{% url 'vinyldestination:index' %}">{{ user.username }}</a></li>
				<li><a href="{% url 'vinyldestination:records' %}">Browse</a></li>
				<li><a href="{% url 'settings' %}">Settings</a></li>
				<li><a href="{% url 'vinyldestination:logout' %}">Logout</a></li>
			</ul>
			{% else %}
			<form id="login_form" method="post" action="{% url 'vinyldestination:login' %}">
				{% csrf_token %}
				Username: <input type="text" id="input_field" name="username" value=""/>
				Password: <input type="password" id="input_field" name="password" value=""/>
				<input type="submit" id="button" value="Sign In"/>
				</br>
				</br>
				or sign in using
				<a href="{% url 'social:begin' 'github' %}"><img id="socials" src="{% static 'images/github.png' %}" alt="github"/></a>
				<a href="{% url 'social:begin' 'facebook' %}"><img id="socials" src="{% static 'images/facebook.png' %}" alt="facebook"/></a>
				<a href="{% url 'social:begin' 'twitter' %}"><img id="socials" src="{% static 'images/twit.png' %}" alt="twitter"></a>
			</form>
			{% endif %}
		</div>
	</div>

	{% block body_block %}
	{% get_artist_list artist %}
	{% endblock %}

	</body>
</html>

templates/vinyldestination/index.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block title_block %}
Vinyl Destination
{% endblock %}

{% block body_block %}

{% if user.is_authenticated %}

<div class = "home">
	<h1>Top Rated Records</h1>
		<div class = "records">
			{% if records %}
				{% for record in records %}
				<a href="{% url 'vinyldestination:records' %}{{ record.slug }}/"><img id="recordartwork" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
					{% endfor %}
			{% else %}
			There are no records present.
			{% endif %}
		</div>
</div>

{% else %}

<div class = "welcome">
	<div class = "info">
		<h2>vinyldestination, the most convenient way to manage and grow your vinyl collection.</h2>
	</div>
	<div class = "register">
		{{ form.non_field_errors }}
		<form id="form" method="post" action="{% url 'vinyldestination:register' %}"
			  enctype="multipart/form-data">
			{% csrf_token %}
			<ul id="fields">
				<h2>New here? Create a free account!</h2>
				{{ user_form.as_ul }}
				{{ profile_form.as_ul }}
			</ul>
			<div class = terms>
				<input type="submit" id="button" name="submit" value="Sign Up"/>
				<p>by clicking "Sign Up" I agree to the vinyldestination Terms of Service and confirm that I am at least 13 years old</p>
			</div>
		</form>
	</div>
{% endif %}
</div>

{% if user.is_authenticated %}
<h1>Trending records</h1>
{% else %}
<h3>Trending records</h3>
{% endif %}
		<div class = "records">
			{% if trending %}
				{% for record in trending %}
				<a href="{% url 'vinyldestination:records' %}{{ record.slug }}/"><img id="recordartwork" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
					{% endfor %}
			{% else %}
			There are no records present.
			{% endif %}
		</div>

{% endblock %}

templates/vinyldestination/login.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block head %}
<link href="{% static 'css/basic/final_admin.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
{% endblock %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}

<div class = admin>

	<div class = "header">
		<a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>
	</div>

	{% if user.is_authenticated %}
	<p>You are already logged in as {{ user.username }}</p>
	<a href="{% url 'vinyldestination:logout' %}">Logout?</a>
	{% else %}
	<h2>Login to vinyldestination</h2>
	<form id="form" method="post" action="{% url 'vinyldestination:login' %}">
		{% csrf_token %}
		Username:
		<input type="text" name="username" value=""/>
		Password:
		<input type="password" name="password" value=""/>
		<p><input type="submit" id="button" value="submit" /></p>
	</form>
	<a href="{% url 'social:begin' 'github' %}">Login with GitHub</a>
	<br/>
	<a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
	<br/>
	<a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a>
	{% endif %}

</div>

{% endblock %}

templates/vinyldestination/password.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block head %}
<link href="{% static 'css/basic/final_admin.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
{% endblock %}

{% block title_block %}
Change Password
{% endblock %}

{% block body_block %}

<div class = admin>

    <div class = "header">
        <a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>
    </div>

    <h3>Change Password</h3>
    {% if not user.has_usable_password %}
        <p>You have not defined a password yet.</p>
    {% endif %}
    <form id="form" method="post">
        {% csrf_token %}
        <ul>
        {{ form.as_ul }}
        </ul>
        <p><button type="submit" id="button">Save changes</button></p>
    </form>

</div>

{% endblock %}

templates/vinyldestination/record.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}
{% load ratings %}

{% block title_block %}
	{% if record %}
	{{record.a_id}} - {{record.name}}
    {% else %}
    Unknown Artist - Unknown Record
    {% endif %}
{% endblock %}

{% block body_block %}

<div class = "maincontainer">

	<div class = "recordcontainer">
		{% if record %}
		<h4>{{record.name}} by {{record.a_id}}</h4>
		</br>
		<div class = "statscontainer">
				<img id="singleimage" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
			<div class = "stats">
				Released in {{record.year}}</br>
				Genre: {{record.genre}}</br>
				Likes: {{record.likes}}</br>
				Views: {{record.views}}</br>
				{% block content %}
				{% ratings record %}
				{% endblock content %}
				{% if user.is_authenticated %}</br>
				<a id="reviewbutton" href="/vinyldestination/records/{{ record.slug }}/add_review" title="review">Leave A Review</a>
				{% endif %}
			</div>
		</div>
	{% endif %}
		</br>
		<div class = "recorddescription">
			{{record.description}}
		</div>
	</div>

	<div class = "artistcontainer">
		{% if artist %}
		<h4>About the artist:</h4>
		</br>
		<div class = "artistimagecontainer">
			<img id="artistimage" src="{{MEDIA_URL}}{{ artist.image }}" alt="{{ record.name }}"></a>
		</div>
		</br>
		<div class = "artistdescription">
			{{artist.description}}
		</div>
	</div>

	{% endif %}
</div>

<div class = "similar">
	<h2>Similar records in {{record.genre}}</h2>
	{% if similar %}
	{% for record in similar%}
	<a href="/vinyldestination/records/{{ record.slug }}/"><img id="recordartwork" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
	{% endfor %}
	{% else %}
	<h3>There are no records present.</h3>
	{% endif %}
</div>

<div class = "reviews">
	<h2>Reviews of {{record.name}}</h2>
	{% if review %}
	{% for review in review %}
	<div class = singlereview>
		<h5>{{review.title}} by {{review.author}}</h5>
		<p>{{review.review}}</p>
	</div>
	</br>
	{% endfor %}
	{% else %}
	<div class = singlereview>
		There are no reviews present.
	</div>
	</br>
	{% endif %}
	{% endblock body_block%}
</div>

templates/vinyldestination/records.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block title_block %}
Browse All Records
{% endblock %}

{% block body_block %}

<h1>All Records</h1>

<div>
	{% if records_all %}
	<ul>
		{% for record in records_all %}
		<a href="{% url 'vinyldestination:records' %}{{ record.slug }}/"><img id="recordartwork" src="{{MEDIA_URL}}{{ record.image }}" alt="{{ record.name }}"></a>
		{% endfor %}
	</ul>
	{% else %}
	There are no records present.
	{% endif %}
</div>

{% endblock %}

templates/vinyldestination/register.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block head %}
<link href="{% static 'css/basic/final_admin.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
{% endblock %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}

<div class = admin>

	<div class = "header">
		<a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>
	</div>

	{% if user.is_authenticated %}
	<p>You are already logged in as {{ user.username }}</p>
	<a href="{% url 'vinyldestination:logout' %}">Logout?</a>
	{% else %}
	<h2>Register for vinyldestination</h2>
	{% if registered %}
	Thank you for registering!
	<a href="{% url 'vinyldestination:index' %}">Return to the homepage.</a><br/>
	{% else %}
	<form id="form" method="post" action="{% url 'vinyldestination:register' %}"
		  enctype="multipart/form-data">
		{% csrf_token %}
		<ul>
		{{ user_form.as_ul }}
		{{ profile_form.as_ul }}
		</ul>
		<p><input type="submit" id="button" name="submit" value="Register"/></p>
	</form>

	{% endif %}
	{% endif %}

</div>

{% endblock %}

templates/vinyldestination/settings.html
{% extends 'vinyldestination/base.html' %}
{% load staticfiles %}

{% block head %}
<link href="{% static 'css/basic/final_admin.css' %}" rel="stylesheet" title="basicstyle" type="text/css"/>
{% endblock %}

{% block title_block %}
Settings
{% endblock %}

{% block body_block %}

<div class = admin>

  <div class = "header">
    <a href="{% url 'vinyldestination:index' %}"><img id="logo" src="{% static 'images/logo.png' %}" alt="Vinyl Destination"/></a>
  </div>

  <h3>GitHub</h3>
  {% if github_login %}
    <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">{{ github_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'github' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from GitHub</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from GitHub</button>
      <p>You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Github.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
  {% endif %}

  <h3>Facebook</h3>
  {% if facebook_login %}
    <p>Connected as <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/" target="_blank">{{ facebook_login.extra_data.id }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from Facebook</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from Facebook</button>
      <p>You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Facebook.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
  {% endif %}

  <h3>Twitter</h3>
  {% if twitter_login %}
    <p>Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">@{{ twitter_login.extra_data.access_token.screen_name }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'twitter' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from Twitter</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from Twitter</button>
      <p>You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Twitter.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'twitter' %}">Connect to Twitter</a>
  {% endif %}

  <h3>Change Password</h3>
  <a href="/settings/password">Change Password</a>

</div>

{% endblock %}